services:
  postgres:
    image: postgres
    container_name: postgres
    restart: always
    ports:
      - 5433:5432
    env_file:
      - .env
    environment:
      - POSTGRES_DB=different
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./database:/var/lib/postgresql/
  server:
    image: different
    depends_on:
      - postgres
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/different
    restart: on-failure
    ports:
      - 8000:8000
