const Typesense = require("typesense");
const LISTINGS_COLLECTION_NAME = "listings";

const TYPESENSE_CONFIG = {
  nodes: [
    {
      host: "o2by0uh958xjn1igp-1.a1.typesense.net",
      port: 443,
      protocol: "https",
    },
  ],
  apiKey: "2HrzvdCDAAk2kvCsRO8M0s9Gryork7Qv",
};

const typesense = new Typesense.Client(TYPESENSE_CONFIG);

const DESIGNERS = [
  "A Cold Wall",
  "A.P.C.",
  "Ami",
  "Abercrombie & Fitch",
  "Acne Studios",
  "Acronym",
  "Adidas",
  "Aeronautica Militare",
  "Affliction",
  "Aime Leon Dore",
  "Airwalk",
  "Alexander Mcqueen",
  "Alexander Wang",
  "Alfred Dunhill",
  "Allsaints",
  "Alpha Industries",
  "Alstyle Tag",
  "Alyx",
  "Ambush Design",
  "Amiri",
  "Andy Warhol",
  "Anti Social Social Club",
  "Anvil Tag",
  "Arc'teryx",
  "Armani",
  "Armani Exchange",
  "Aspesi",
  "Asos",
  "Avirex",
  "AWGE",
  "Baldinini",
  "Balenciaga",
  "Bally",
  "Balmain",
  "Banana Republic",
  "Bape",
  "Baracuta",
  "Barbour",
  "Belstaff",
  "Ben Sherman",
  "Ben Davis",
  "Ben Taverniti Unravel Project",
  "Benetton",
  "Beretta",
  "Berghaus",
  "Bershka",
  "Big John",
  "Billabong",
  "Billionaire Boys Club",
  "Billionaire Couture",
  "Birkenstock",
  "Black Diamond",
  "Blue Blue Japan",
  "Bogner",
  "Boggi",
  "Boneville",
  "Boris Bidjan Saberi",
  "Born X Raised",
  "Bottega Veneta",
  "Brain Dead",
  "Brioni",
  "Brooks",
  "Brunello Cucinelli",
  "Buffalo London",
  "Bugatti",
  "Burberry",
  "Burberry Prorsum",
  "Burton",
  "Bvlgari",
  "C&A",
  "C.p. Company",
  "Comme des Garcons",
  "Cabelas",
  "Cabane De Zucca",
  "Cactus Plant Flea Market",
  "Callaway",
  "Calvin Klein",
  "Camel",
  "Canada Goose",
  "Canali",
  "Carhartt",
  "Carhartt Wip",
  "Carlo Colucci",
  "Carrera",
  "Cartier",
  "Cav Empt",
  "Cedar Wood State",
  "Celine",
  "Cerruti 1881",
  "Champion",
  "Christian Audigier",
  "Christian Dior",
  "Christian Louboutin",
  "Chrome Hearts",
  "Clarks",
  "Coach",
  "Cole Haan",
  "Columbia",
  "Chanel",
  "Chaps",
  "Cheap Monday",
  "Comme Ca Ism",
  "Common Projects",
  "Converse",
  "Coogi",
  "Corneliani",
  "Crocs",
  "Dkny",
  "Daks London",
  "Dale Of Norway",
  "Daniel Hechter",
  "Defend Paris",
  "Denim And Supply Ralph Lauren",
  "Desigual",
  "Diamond Supply Co",
  "Dickies",
  "Diesel",
  "Dime",
  "Dirk Bikkembergs",
  "Disney",
  "Dockers",
  "Dolce & Gabbana",
  "Dr. Martens",
  "Dries Van Noten",
  "Drop Dead",
  "Dsquared2",
  "Duck Head",
  "Dunlop",
  "Dupe",
  "Eastpak",
  "Ecco",
  "Ecko Unltd.",
  "Ed Hardy",
  "Eddie Bauer",
  "Edwin",
  "Element",
  "Ellesse",
  "Emporio Armani",
  "Engineered Garments",
  "Eric Emanuel",
  "Ermenegildo Zegna",
  "Escada",
  "Etnies",
  "Eton",
  "Etro",
  "Everlast",
  "Evisu",
  "Farah",
  "Fay",
  "Fcuk",
  "Fear Of God",
  "Fendi",
  "Ferrari",
  "Fila",
  "Filling Pieces",
  "Filson",
  "Final Home",
  "Fiorucci",
  "Fjallraven",
  "Fox",
  "Fragment Design",
  "Fred Perry",
  "Freitag",
  "French Connection",
  "Fruit Of The Loom Tag",
  "Fuck The Population",
  "Fucking Awesome",
  "Fuct",
  "Full Send By Nelk Boys",
  "Furla",
  "Futura",
  "G-Star Raw",
  "Gap",
  "General Research",
  "George",
  "Gianfranco Ferre",
  "Gildan Tag",
  "Giorgio Armani",
  "Giuseppe Zanotti",
  "Givenchy",
  "Global Work",
  "Golden Goose",
  "Goldwin",
  "Golf Wang",
  "Golf Le Fleur",
  "Gore Wear",
  "Gosha Rubchinskiy",
  "Greg Norman",
  "Gucci",
  "Guess",
  "H&M",
  "Hackett",
  "Haglofs",
  "Haider Ackermann",
  "Hai Sporting Gear",
  "Hanes Tag",
  "Hard Rock Cafe",
  "Harley Davidson",
  "Harris Tweed",
  "Helly Hansen",
  "Helmut Lang",
  "Hermes",
  "Herno",
  "Heron Preston",
  "Herschel",
  "Hiroko Koshino Homme",
  "Hogan",
  "Hoka One One",
  "Hollister",
  "Huf",
  "Hugo Boss",
  "Hummel",
  "Hysteric Glamour",
  "Iceberg",
  "Icecream",
  "Independent",
  "Isabel Marant",
  "Isaia",
  "Issey Miyake",
  "Izod",
  "J.crew",
  "J.lindeberg",
  "J.w.anderson",
  "Jack & Jones",
  "Jack Wills",
  "Jack Wolfskin",
  "Jacob Cohen",
  "Jacquemus",
  "Jean Charles De Castelbajac",
  "Jean Michel Basquiat",
  "Jean Paul Gaultier",
  "Jil Sander",
  "John Bull",
  "John Deere",
  "John Elliott",
  "John Galliano",
  "Jordan",
  "Joop!",
  "Juicy Couture",
  "Julius",
  "Jun Takahashi",
  "Junko Shimada",
  "Junya Watanabe",
  "Just Cavalli",
  "K Swiss",
  "Kangol",
  "Kansai Yamamoto",
  "Kapital",
  "Kappa",
  "Karhu",
  "Karl Helmut",
  "Karl Kani",
  "Karl Lagerfeld",
  "Katharine Hamnett",
  "Kaws",
  "Kazuki Kuraishi",
  "Keith Haring",
  "Kenneth Cole",
  "Kenzo",
  "Kiton",
  "KITH",
  "Kojima Genes Japan",
  "Ksubi",
  "Lrg",
  "La Martina",
  "La Sportiva",
  "Lacoste",
  "Lambretta",
  "Lands End",
  "Lanvin",
  "Lauren Ralph Lauren",
  "Le Coq Sportif",
  "L.l. Bean",
  "Lee",
  "Left Hand",
  "Liquid Blue Tag",
  "Loewe",
  "Logo 7 Tag",
  "London Fog",
  "Lonsdale",
  "Loro Piana",
  "Lotto",
  "Louis Vuitton",
  "Lucky Brand",
  "Lyle & Scott",
  "M+rc Noir",
  "Mcm",
  "Ma.strum",
  "Maharishi",
  "Maison Kitsune",
  "Maison Margiela",
  "Mambo",
  "Mammut",
  "Mandarina Duck",
  "Marc Jacobs",
  "Marc O Polo",
  "Marcelo Burlon",
  "Margaret Howell",
  "Marithe Francois Girbaud",
  "Marks And Spencer",
  "Marlboro",
  "Marmot",
  "Marni",
  "Marshall Artist",
  "Martine Rose",
  "Massimo Dutti",
  "Mastermind Japan",
  "Max Mara",
  "Mcgregor",
  "Members Only",
  "Michael Kors",
  "Michiko Koshino",
  "Miharayasuhiro",
  "Mustang",
  "Misbhv",
  "Mishka",
  "Missoni",
  "Mitchell & Ness",
  "Miu Miu",
  "Mizuno",
  "Moncler",
  "Montbell",
  "Moschino",
  "Mountain Equipment Co Op",
  "Msgm",
  "Mugler",
  "Mulberry",
  "Naked & Famous",
  "Napapijri",
  "Native",
  "Nautica",
  "Neil Barrett",
  "Nepenthes New York",
  "New Balance",
  "New Era",
  "New Rock",
  "Nigel Cabourn",
  "Nike",
  "Nike Acg",
  "Noah",
  "Norrona",
  "Norse Projects",
  "Nudie Jeans",
  "Number (n)ine",
  "Nutmeg Tag",
  "Obey",
  "Octobers Very Own",
  "Off-white",
  "Old Navy",
  "Oneill",
  "Onitsuka Tiger",
  "Oakley",
  "Oshkosh",
  "Our Legacy",
  "PPFM",
  "Pacsun",
  "Palace",
  "Pal Zileri",
  "Palm Angels",
  "Parajumpers",
  "Patagonia",
  "Patta",
  "Paul & Shark",
  "Paul Smith",
  "Peanuts",
  "Pelle Pelle",
  "Pendleton",
  "Penfield",
  "People Of The Labyrinths",
  "Pepe Jeans",
  "Perry Ellis",
  "Philipp Plein",
  "Pierre Balmain",
  "Pierre Cardin",
  "Places + Faces",
  "Planet Hollywood",
  "Playboy",
  "Pleasures",
  "Polar Skate Co.",
  "Polo Ralph Lauren",
  "Porter",
  "Porsche",
  "Prada",
  "Premiata",
  "Pro Player",
  "Prps",
  "Pull & Bear",
  "Puma",
  "Quiksilver",
  "Raf Simons",
  "Rag & Bone",
  "Ralph Lauren",
  "Rapha",
  "RayBan",
  "Red Wing",
  "Reebok",
  "Religion",
  "Renoma",
  "Replay",
  "Represent Clo.",
  "Revenge",
  "Rhude",
  "Rick Owens",
  "Rick Owens Drkshdw",
  "Riot Division",
  "Rip Curl",
  "Rip N Dip",
  "River Island",
  "Robert Geller",
  "Roberto Cavalli",
  "Robins Jeans",
  "Rodeo Crowns",
  "Roots",
  "Russell Athletic",
  "Saint Laurent Paris",
  "Saint Michael",
  "Saks Fifth Avenue",
  "Salomon",
  "Salvatore Ferragamo",
  "Samsoe & Samsoe",
  "Sandro",
  "Santa Cruz",
  "Santoni",
  "Saucony",
  "Schott",
  "Scotch & Soda",
  "Screen Stars Tag",
  "Selected Homme",
  "Seraphin",
  "Sergio Tacchini",
  "Skechers",
  "Snipes",
  "Spellbound",
  "Spider Worldwide",
  "Staff",
  "Stefano Ricci",
  "Stella McCartney",
  "Steve Madden",
  "Stone Island",
  "Strellson",
  "Stussy",
  "Superdry",
  "Supreme",
  "Takahiromiyashita The Soloist.",
  "Takashi Murakami",
  "Takeo Kikuchi",
  "Ted Baker",
  "The Hundreds",
  "The Kooples",
  "The North Face",
  "Theory",
  "Thom Browne",
  "Thrasher",
  "Tiffany & Co.",
  "Tod's",
  "Tom Ford",
  "Tom Tailor",
  "Tommy Bahama",
  "Tommy Hilfiger",
  "Tommy Jeans",
  "Topman",
  "Tornado Mart Japan",
  "Tory Burch",
  "Trapstar London",
  "True Religion",
  "Trussardi",
  "Tsumori Chisato",
  "Tultex Tag",
  "U.s. Polo Assn.",
  "Ugg",
  "Umbro",
  "Undefeated",
  "Under Armour",
  "Undercover",
  "Uniqlo",
  "United Arrows",
  "United Colors Of Benetton",
  "Urban Outfitters",
  "Valentino",
  "Van Heusen",
  "Vans",
  "Versace",
  "Versus Versace",
  "Vetements",
  "Visvim",
  "Vivienne Westwood",
  "Vlone",
  "Vogue",
  "Voi Jeans Co.",
  "Volcom",
  "Von Dutch",
  "Wacko Maria",
  "Wallace & Barnes",
  "Walter Van Beirendonck",
  "Warren Lotas",
  "Weekday",
  "Wellensteyn",
  "White Mountaineering",
  "Wilson Athletics",
  "Wings + Horns",
  "Wood Wood",
  "Woolrich John Rich & Bros.",
  "Wrangler",
  "Wu Tang Clan",
  "Y-3",
  "Yeezy",
  "Yeezy Season",
  "Yohji Yamamoto",
  "Yoshiyuki Konishi",
  "Yves Saint Laurent",
  "Zegna",
  "Zara",
  "Zilli",
  "Merch",
  "Custom",
  "Readymade",
  "Etudes",
  "Ienki Ienki",
  "Unknown",
];

const TAGS = [
  "#Luxury",
  "#Vintage",
  "#Collaboration",
  "#Streetwear",
  "#Outdoor",
  "#Custom Made",
  "#Music Band",
  "#Japanese",
  "#Celebrity",
  "#Merch",
  "#Hypebeast",
  "#Skateboarding",
  "#Military",
  "#Drill",
  "#Sport",
  "#Nature",
  "#Movie",
  "#Humor",
  "#Racing",
  "#American",
  "#Camo",
  "#Distressed",
  "#Leather",
  "#Limited",
  "#Archival",
  "#Pockets",
  "#Minimalism",
];

const SIZES = [
  "US XXS / EU 40",
  "US XS / EU 42",
  "US S / EU 44-46",
  "US M / EU 48-50",
  "US L / EU 52-54",
  "US XL / EU 56",
  "US XXL / EU 58",
];

const CATEGORIES = [
  "T-shirts",
  "Long sleeve t-shirts",
  "Polo shirts",
  "Shirts button up",
  "Sweaters",
  "Hoodies",
  "Sweatshirts",
];

const conditions = [
  "New with tags",
  "Several times worn",
  "Gently used",
  "Used",
  "Very worn",
];

const createDataSet = () => {
  const dataSet = [];

  for (let index = 0; index < 5; index++) {
    const listing = {
      id: index.toString(),
      title: "Gucci glasses",
      designer: DESIGNERS[Math.floor(Math.random() * DESIGNERS.length)],
      tags: [TAGS[Math.floor(Math.random() * TAGS.length)]],
      category: CATEGORIES[Math.floor(Math.random() * CATEGORIES.length)],
      imageUrls: [
        "https://s3.eu-central-1.amazonaws.com/different.dev/tRPUfBh1TxSxNI-LSlmbVQ-0",
      ],
      condition: conditions[Math.floor(Math.random() * conditions.length)],
      price: Math.floor(Math.random() * 10000),
      size: SIZES[Math.floor(Math.random() * SIZES.length)],
      status: "AVAILABLE",
    };
    dataSet.push(listing);
  }
  return dataSet;
};

const seed = async () => {
  const dataSet = createDataSet();
  try {
    console.log("Creating dataset...");
    await typesense
      .collections(LISTINGS_COLLECTION_NAME)
      .documents()
      .import(dataSet, { action: "create" });
  } catch (err) {
    console.error(err);
  }
};

seed();
